name: rmd_koval_ki407_lab2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.0
  image_picker: ^1.1.2
  audioplayers: ^6.1.0
  path_provider: ^2.0.0
  provider: ^6.1.2
  firebase: ^9.0.3
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon.jpg
    - assets/music/cola.mp3