name: rmd_koval_ki407_lab2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
   sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.0
  image_picker: ^1.1.2
  audioplayers: ^6.1.0
  path_provider: ^2.0.0
  provider: ^6.1.2
  firebase: ^9.0.3
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.3
  connectivity_plus: ^6.0.5
  autologin: ^1.0.0
  internet_connection_checker_plus: ^1.0.1
  http: ^0.13.4
  sqflite: ^2.0.0+4
  crypto: ^3.0.0
  supabase_flutter: ^0.3.0
  flutter_light_plugin:
    path: flutter_light_plugin
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true 
  disable-swift-package-manager: true 
  assets:
    - assets/images/icon.jpg
    - assets/music/cola.mp3
    - assets/music/time.mp3
    - assets/music/die.mp3
    - assets/music/wc.mp3
    - assets/music/ultraviolence.mp3